sudo: required
language: python
dist: xenial
matrix:
  include:
    # https://docs.python.org/devguide/#status-of-python-branches
    # One build pulls latest versions dynamically
    - python: 3.8
      env: CDH=cdh5 CDH_VERSION=5 PRESTO=RELEASE
    - python: 3.7
      env: CDH=cdh5 CDH_VERSION=5 PRESTO=RELEASE
    - python: 3.6
      env: CDH=cdh5 CDH_VERSION=5 PRESTO=RELEASE
    - python: 3.6
      env: CDH=cdh5 CDH_VERSION=5.10.1 PRESTO=0.147
    - python: 3.5
      env: CDH=cdh5 CDH_VERSION=5.10.1 PRESTO=0.147
    - python: 3.4
      env: CDH=cdh5 CDH_VERSION=5.10.1 PRESTO=0.147
    - python: 2.7
      env: CDH=cdh5 CDH_VERSION=5.10.1 PRESTO=0.147
install:
  - ./scripts/travis-install.sh
  - pip install codecov
script: PYTHONHASHSEED=random pytest -v
after_success: codecov
